<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>Softphone</AssemblyName>
    <RootNamespace>Softphone</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="6.0.0" />
    <PackageReference Include="SIPSorceryMedia.Windows" Version="1.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>

