// On Windows the entry point is generated by WPF (App.xaml ApplicationDefinition).
// On macOS / Linux (net8.0 TFM) this explicit Main() is the sole entry point.
#if !WINDOWS

using System;
using System.Threading;
using Avalonia;
using Avalonia.Threading;

namespace Softphone
{
    internal static class Program
    {
        [STAThread]
        public static void Main(string[] args)
        {
            // ── Bootstrap DI before any Avalonia window is created ────────────
            CrossPlatformBootstrap.Initialize(
                postToUiThread:        action => Dispatcher.UIThread.Post(action),
                postUrgentToUiThread:  action => Dispatcher.UIThread.Post(action, DispatcherPriority.Send));

            // ── WebRTC: headless stub on macOS / Linux ────────────────────────
            // WebRtcService requires an IWebRtcEngineHost to be attached before
            // any call attempts.  MacLinuxWebRtcEngineHost is a no-op that prevents
            // crashes while WebRTC calls are not yet supported on this platform.
            // Attach via WebRtcService.AttachEngine(...) from the MainWindow ctor
            // once the service is instantiated; the stub is exported below so that
            // other startup code can reference it.
            WebRtcEngineHostPlatform.Current = new MacLinuxWebRtcEngineHost();

            // ── Start Avalonia UI ─────────────────────────────────────────────
            AvaloniaAppBuilder
                .BuildAvaloniaApp()
                .StartWithClassicDesktopLifetime(args);
        }
    }

    /// <summary>
    /// Cross-platform accessor for the active IWebRtcEngineHost instance.
    /// On Windows the host is constructed and attached inside App.xaml.cs.
    /// On macOS/Linux Program.Main() sets it to MacLinuxWebRtcEngineHost.
    /// </summary>
    public static class WebRtcEngineHostPlatform
    {
        public static IWebRtcEngineHost? Current { get; set; }
    }
}

#endif
