// On Windows the entry point is generated by WPF (App.xaml ApplicationDefinition).
// On macOS / Linux (net8.0 TFM) this explicit Main() is the sole entry point.
#if !WINDOWS

using System;
using System.Threading;
using Avalonia;
using Avalonia.Threading;
using Softphone.Platform;

namespace Softphone
{
    internal static class Program
    {
        [STAThread]
        public static void Main(string[] args)
        {
            // ── Single instance + click-to-call forwarding ────────────────────
            // callspire://… / tel: may arrive as an argument (Linux xdg-open, manual launch).
            // On macOS the .app bundle normally receives URLs via application:openURLs:
            // (handled in AvaloniaApp through IActivatableLifetime), but a raw binary launch
            // still goes through here.
            string? protocolUrl = ProtocolActivation.FindInArgs(args);
            var instance = new CrossPlatformSingleInstance();
            if (!instance.TryAcquire())
            {
                if (protocolUrl != null)
                    instance.Forward(protocolUrl);
                else
                    instance.Forward("activate");
                instance.Dispose();
                return;
            }
            if (protocolUrl != null) ProtocolActivation.Enqueue(protocolUrl);

            // ── Bootstrap DI before any Avalonia window is created ────────────
            CrossPlatformBootstrap.Initialize(
                postToUiThread:        action => Dispatcher.UIThread.Post(action),
                postUrgentToUiThread:  action => Dispatcher.UIThread.Post(action, DispatcherPriority.Send));

            instance.StartServer(msg =>
            {
                if (ProtocolActivation.LooksLikeProtocolUrl(msg)) ProtocolActivation.Enqueue(msg);
                else AvaloniaApp.RequestActivate();
            });

            // ── WebRTC ────────────────────────────────────────────────────────
            // The real engine host (Softphone.WebRtc.AvaloniaWebRtcEngineHost over
            // NativeWebView / WKWebView) is created lazily by Avalonia MainWindow via
            // DesktopAppController.WebRtcHostFactory. MacLinuxWebRtcEngineHost remains
            // only as a no-op fallback when the platform has no usable web engine.

            // ── Start Avalonia UI ─────────────────────────────────────────────
            try
            {
                AvaloniaAppBuilder
                    .BuildAvaloniaApp()
                    .StartWithClassicDesktopLifetime(args);
            }
            finally
            {
                instance.Dispose();
            }
        }
    }
}

#endif
