<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Callspire.UpdateServer</RootNamespace>
    <AssemblyName>Callspire.UpdateServer</AssemblyName>
  </PropertyGroup>

</Project>
